### ISSUE TITLE
Cygwin Portable cannot be started. You may wish to re-insstall to fix this.

### ISSUE THREAD

**Issue by danielsokolowski** [MachinaCore/CygwinPortable#34]
Hello, when I download the PAF or 7z file and try to run it I get: 
![image](https://user-images.githubusercontent.com/273413/33397005-5021b016-d518-11e7-8a2c-9df8132ef028.png)

The README.md states: 

"""
First Start

Start CygwinPortable.exe - The setup.exe is download automatically
Choose x86/x64 Version
Let the cygwin install (defaults are cygwin defaults + vim,wget,tar,gawk,bzip2 packages)
Enjoy Cygwin :-)
"""

Please note if I download the older packages with cygwin already downloaded it works.

**Comment by inadavid** [comment]
same problem here. where to download the "older packages with cygwin already downloaded"? @danielsokolowski

**Comment by LORDofDOOM** [comment]
Hi,

Build is fixed -> Please download again
