### ISSUE TITLE
Installing new packages: Setup path clarification

### ISSUE THREAD

**Issue by Fironet** [MachinaCore/CygwinPortable#35]
New to Cygwin and this portable version and was looking to install the Python package within Cygwin.

It appears from a general search new packages are installed to Cygwin via the Setup (found in the tray menu), but I'm not sure which directory to install to (although Cygwin was already installed with CygwinPortable) as the pre-filled path isn't the portable path, and the `CygwinPortable\App\Runtime\Cygwin` directory contains a CygwinPortable binary that I'm unsure will be overwritten if re-installed to.

Essentially looking for some clarification as I couldn't find this in the readme, or a dev email to ask, and wanted to maintain portability.

**Comment by LORDofDOOM** [comment]
Hi,

if you start setup all packages will install to the default portable path. What path is pre-filled in your case ?

**Comment by Fironet** [comment]
The pre-filled path is `C:\Portable`. However, after seeing it again I realized it may be being truncated at the first space in the path I have it in (`C:\Portable Apps\`). Can Cygwin be installed to a path with spaces or is this just a minor hiccup of the setup path detection?

**Comment by LORDofDOOM** [comment]
@Fironet I did not test this, but it is always a better choice to use a path without spaces - Official PortableApps Launcher also don't use spaces
