### ISSUE TITLE
Additional packages not recognised

### ISSUE THREAD

**Issue by llionevans** [MachinaCore/CygwinPortable#37]
Hi, not sure if I'm missing something simple here. After I go through the Cygwin package updater, the new packages aren't recognised "command not found" if I try from a terminal launched via the taskbar icon.

However, if I launch a terminal by navigating to \CygwinPortable\App\Runtime\Cygwin\Cygwin.bat they are recognised.

So I'm just wondering if this is an issue, or a setting change that I've missed that needs to be applied after updating packages.

Thanks in advance for any advice.

**Comment by llionevans** [comment]
Also, I'm not sure if that .bat file is created on installation, but can I suggest that rather than it include the drive letter in the absolute path that '%CD:~0,3%' is used instead?

I found that running the .bat file would fail if the USB drive letter changed (e.g. on a different computer). This should avoid that. (although I probably shouldn't be manually calling the .bat in the first case)

**Comment by LORDofDOOM** [comment]
Hi,

thanks for your report, the Cygwin.bat is getting created by cygwin itself, not by this package, I'll take a look into it and check if we can modify it if Driveletter has changed
