### ISSUE TITLE
Cannot bypass UAC

### ISSUE THREAD

**Issue by mittorn** [MachinaCore/CygwinPortable#38]
When trying to launch cygwin portable, windows asking for admin rights. Is this really a portable app?

**Comment by LORDofDOOM** [comment]
Please check README.md before open issue

> ShellExtensions needs admin rights (Only one time to register the ShellExtension - After successful registration you can run CygwinPortable with UAC enabled). CygwinPortable will run without ShellExtensions, but they are pretty comfortable :-)

**Comment by mittorn** [comment]
I tried to disable, but it does not help. Running cygwin setup and cpnfigurator still needs UAC.
Setup can be fixed by `--no-admin` option for normal installation. Maybe add --no-admin option which will disable shell extension and pass to installer?
