### ISSUE TITLE
Command Line Options for Installer?

### ISSUE THREAD

**Issue by Memphizzz** [MachinaCore/CygwinPortable#39]
Hi,

first of all, thanks for CygwinPortable! Its a great project!

I got some questions though:

Is it possible to have the Installer, silently (no GUI) install to a specified directory? I was thinking something like this:
CygwinPortable.exe -installdir C:\cygwin -packages Default.txt -notray

As you can see I'm trying to automate the installation and would like to set the path to where it will be installed, the packages to install and it would be nice if someone could hide the tray icon.

Of course instead of showing the GUI window of the Cygwin Setup, a progress on command line would be great.

Would this be possible currently or maybe a future version?

Thanks in advance!

MemphiZ

**Comment by LORDofDOOM** [comment]
Hi, 

this is not needed - For automatic deployment you can use the .7z file -> Simply extract and run. If you need additional packages, run on ypuir system -> zip CygwinPortable folder and deploy
