### ISSUE TITLE
No build available

### ISSUE THREAD

**Issue by towe96** [MachinaCore/CygwinPortable#40]
The AppVeyor link to the zipped portable version seens to be dead since AppVeyor deletes content six months after being built.

**Comment by AlexN-114** [comment]
+1

**Comment by AureliaNYT** [comment]
[Here ]( https://ci.appveyor.com/project/AureliaNYT/cygwinpaf/build/artifacts) you go mate =)! 
P.S: I updated some of the libraries, but no breaking changes occoured, so have fun :)

**Comment by LORDofDOOM** [comment]
Rebuilded
