### ISSUE TITLE
Crash upon start

### ISSUE THREAD

**Issue by Michael-1** [MachinaCore/CygwinPortable#43]
Upon running the executable on my Windows-7 machine, I immediately get the feedback that “CygwinPortable has stopped working.”

In the event log I find two related entries. The first one is from the .NET runtime:

> Application: CygwinPortable.exe
> CoreCLR Version: 4.6.27121.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.TypeLoadException: Could not load type 'System.Security.IStackWalk' from assembly 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>   at System.Windows.Forms.Application.EnableVisualStyles()
>   at CygwinPortableCS.Program.Main() in C:\projects\cygwinportable\Source\Program.cs:line 21

The second one is the “application error” itself:

> Faulting application name: CygwinPortable.exe, version: 1.0.0.0, time stamp: 0x5bf60478
> Faulting module name: KERNELBASE.dll, version: 6.1.7601.24511, time stamp: 0x5d3fa9ff
> Exception code: 0xe0434352
> Fault offset: 0x000000000000b87d
> Faulting process id: 0xb40
> Faulting application start time: 0x01d5696a57ab14cd
> Faulting application path: C:\Programme\Cygwin\App\CygwinPortable.exe
> Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
> Report Id: 9590c0c6-d55d-11e9-81b9-00a0c6000012

**Comment by LORDofDOOM** [comment]
Check the latest version with netcore - Anyway, Windows 7 is not supported (support by microsoft is also no longer available). Newer build only support x64 - if you need to build for Win 7 x86 please compile CygwinPortable on your system
