### ISSUE TITLE
Download is DEAD

### ISSUE THREAD

**Issue by jpgochile** [MachinaCore/CygwinPortable#44]
https://ci.appveyor.com/project/MachinaCore/cygwinportable/build/artifacts ->DEAD

;(

**Comment by AureliaNYT** [comment]
[Here ]( https://ci.appveyor.com/project/AureliaNYT/cygwinpaf/build/artifacts) you go mate =)! 
P.S: I updated some of the libraries, but no breaking changes occoured, so have fun :)

**Comment by LORDofDOOM** [comment]
Rebuilded :-)
